
import { OrderTypes } from "./types";

import type { SortClassMembersConfig } from "./types";

export const defaultOptions: SortClassMembersConfig = {
    accessorPairPositioning: "any",
    alphabetical: true,
    groupPrivateWithAccessors: true,
    // TODO: use these groupings: https://typescript-eslint.io/rules/member-ordering/
    groups: {
        "accessor-pairs": [{ accessorPair: true }],
        "arrow-function-properties": [{ propertyType: "ArrowFunctionExpression" }],
        "async-methods": [{ async: true, type: "method" }],
        "constructor": [{ name: "constructor", type: OrderTypes.method }],
        "conventional-private-methods": [{ name: "/_.+/", type: "method" }],
        "conventional-private-properties": [{ name: "/_.+/", type: "property" }],
        // "event-handlers": [{ name: "/on.+/", type: "method" }, "[conventional-private-methods]"],
        "everything-else": [{}],
        "getters": [{ kind: "get" }],
        "methods": [{ type: "method" }],
        "private-methods": [{ accessibility: "private", type: "method" }],
        "private-properties": [{ accessibility: "private", type: "property" }],
        "properties": [{ type: "property" }],
        "protected-methods": [{ accessibility: "protected", type: "method" }],
        "protected-properties": [{ accessibility: "protected", type: "property" }],
        "public-methods": [{ accessibility: "public", type: "method" }],
        "public-properties": [{ accessibility: "public", type: "property" }],
        "setters": [{ kind: "set" }],
        "static-methods": [{ static: true, type: "method" }],
        "static-properties": [{ static: true, type: "property" }],
        // "accessor-pairs": [{ accessorPair: true }],
        // "arrow-function-properties": { propertyType: "ArrowFunctionExpression" },
        // "async-methods": { async: true, type: "method" },
        // "constructor": { name: "constructor", type: OrderTypes.method },
        // "conventional-private-methods": { name: "/_.+/", type: "method" },
        // "conventional-private-properties": { name: "/_.+/", type: "property" },
        // // "event-handlers": [{ name: "/on.+/", type: "method" }, "[conventional-private-methods]"],
        // "everything-else": {},
        // "getters": { kind: "get" },
        // "methods": { type: "method" },
        // "properties": { type: "property" },
        // "setters": { kind: "set" },
        // "static-methods": { static: true, type: "method" },
        // "static-properties": { static: true, type: "property" },
    },
    locale: "en-US",
    order: [
        "[static-properties]",
        "[static-methods]",
        "[public-properties]",
        "[protected-properties]",
        "[private-properties]",
        "[properties]",
        "constructor",
        // "[event-handlers]", // reference the custom group defined in the "groups" property
        "[getters]",
        "[public-methods]",
        "[protected-methods]",
        "[private-methods]",
        "[methods]",
        "[conventional-private-methods]",
        "[everything-else]",
    ],
    sortInterfaces: false,
    stopAfterFirstProblem: true,
};
