name: Publish

on:
    workflow_dispatch:
        inputs:
            run-id:
                description: run-id
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: echo ${{ inputs.run-id }}

            - name: Download a Build Artifact
              uses: actions/download-artifact@v5.0.0
              with:
                  name: dist
                  # path: # optional
                  run-id: 18704398882 # optional, default is ${{ github.run_id }}
