name: Publish

on:
    workflow_dispatch:
        inputs:
            run_id:
                description: run_id
                required: true
                type: string
                on:


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Download a Build Artifact
              uses: actions/download-artifact@v5.0.0
              with:
                  name: dist
                  run-id: ${{inputs.run_id}}

            - run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
