name: Release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup PNPM
              run: |
                  curl -fsSL https://get.pnpm.io/install.sh | sh -
                  echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
                  echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Cache PNPM store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Cache node_modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}

            - name: Test
              run: pnpm test

            - name: Build
              run: pnpm build

            - run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
